[Desktop Entry]
Type=Application
Version=1.0
Name=QX11Grab
Name[de]=QX11Grab
Name[cs]=QX11Grab
GenericName=Record Desktops
GenericName[de]=Arbeitsfläche Aufnehmen
Comment=A Application to record X11 desktops
Comment[de]=Ein Programm zum aufnehmen von X11 Arbeitsflächen
Exec=qx11grab
Icon=qx11grab
MimeType=
Categories=Qt;KDE;Utility;Applet;X-KDE-Desktop-Applet;
StartupNotify=true
X-DBUS-ServiceName=@QX11GRAB_DBUS_DOMAIN_NAME@
X-DBUS-ServiceType=Unique
OnlyShowIn=KDE;
X-KDE-StartupNotify=false
X-KDE-autostart-phase=2
X-KDE-autostart-condition=qx11grabrc:General:Autostart:true
X-KDE-autostart-after=plasma
X-KDE-AutoEmbed=false
X-KDE-SubstituteUID=false
